spring.application.name=spring_boot_data

spring.datasource.url=jdbc:postgresql://localhost:5432/facepay_db
spring.datasource.username=postgres
spring.datasource.password=123321
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
