spring:
  application:
    name: kafka-config
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:kafka-config-workflow}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    topic:
      workflow-notification: ${APP_KAFKA_TOPIC_WORKFLOW_NOTIFICATION:room-workflow-notification}
      workflow-email: ${APP_KAFKA_TOPIC_WORKFLOW_EMAIL:room-workflow-email}
  demo1:
    base-url: ${APP_DEMO1_BASE_URL:http://localhost:8082}

server:
  port: ${SERVER_PORT:8083}
