spring:
  application:
    name: demo1

  datasource:
    url: ${JASPER_DATASOURCE_URL:jdbc:postgresql://localhost:5432/miniWeb}
    username: ${JASPER_DATASOURCE_USERNAME:postgres}
    password: ${JASPER_DATASOURCE_PASSWORD:123321}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://127.0.0.1:8080/realms/master}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://127.0.0.1:8080}
  realm: ${KEYCLOAK_REALM:master}

app:
  auth:
    google:
      redirect-uri: ${APP_AUTH_GOOGLE_REDIRECT_URI:http://localhost:4200/}
  keycloak:
    browser:
      client-id: ${KEYCLOAK_BROWSER_CLIENT_ID:demo-fe}
      client-secret: ${KEYCLOAK_BROWSER_CLIENT_SECRET:}
      token-uri: ${KEYCLOAK_BROWSER_TOKEN_URI:http://127.0.0.1:8080/realms/master/protocol/openid-connect/token}
      auth-uri: ${KEYCLOAK_BROWSER_AUTH_URI:http://127.0.0.1:8080/realms/master/protocol/openid-connect/auth}

    remote-federation:
      client-id: demo-fe
      client-secret: ${KEYCLOAK_REMOTE_CLIENT_SECRET:}
      token-uri: ${KEYCLOAK_REMOTE_TOKEN_URI:http://127.0.0.1:8080/realms/master/protocol/openid-connect/token}
    admin:
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:}
      client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
      token-realm: ${KEYCLOAK_ADMIN_TOKEN_REALM:}

  user-storage:
    jdbc:
      url: ${USER_STORAGE_JDBC_URL:jdbc:postgresql://localhost:5432/miniWeb}
      username: ${USER_STORAGE_JDBC_USER:postgres}
      password: ${USER_STORAGE_JDBC_PASSWORD:123321}

server:
  port: ${SERVER_PORT:8082}
